# Generated by Django 4.2.1 on 2023-06-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
